name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install mermaid-filter globally
        run: npm install -g mermaid-filter

      - name: Install pandoc and LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown with Mermaid diagrams to PDF
        env:
          NODE_OPTIONS: "--no-sandbox"
        run: pandoc -F mermaid-filter -o Structural_Functional_Diagrams.pdf Structural_Functional_Diagrams.md --pdf-engine=xelatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Structural_Functional_Diagrams
          path: Structural_Functional_Diagrams.pdf
