name: Convert Markdown with Mermaid to PDF

on:
  push:
    branches:
      - main  # أو الفرع الذي تريد تتبع التغييرات عليه

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run pandoc with mermaid-filter
        uses: net9-oy/pandoc-mermaid-action@main
        with:
          input-file: "B2C_B2B/Structural_Functional_Diagrams.md"
          output-file: "Structural_Functional_Diagrams.pdf"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Structural_Functional_Diagrams
          path: Structural_Functional_Diagrams.pdf
